;;; plantuml-stdlib-gcp.el --- PlantUML GCP Components  -*- lexical-binding: t; -*-

;; Author: shyam
;;; Commentary:

;; Components extracted from https://github.com/Crashedmind/PlantUML-icons-GCP from tag `v6.0'

;;; Code:
(require 'cl-generic)

(defconst plantuml-gcp-components
  '(("Cloud_Mobile_App" . "Management_Tools/Cloud_Mobile_App")
    ("Cloud_Console" . "Management_Tools/Cloud_Console")
    ("Debugger" . "Management_Tools/Debugger")
    ("Trace" . "Management_Tools/Trace")
    ("Cloud_Billing_API" . "Management_Tools/Cloud_Billing_API")
    ("Stackdriver" . "Management_Tools/Stackdriver")
    ("Cloud_Shell" . "Management_Tools/Cloud_Shell")
    ("Logging" . "Management_Tools/Logging")
    ("Profiler" . "Management_Tools/Profiler")
    ("Cloud_APIs" . "Management_Tools/Cloud_APIs")
    ("Error_Reporting" . "Management_Tools/Error_Reporting")
    ("Cloud_Deployment_Manager" . "Management_Tools/Cloud_Deployment_Manager")
    ("Cloud_Service_Mesh" . "Management_Tools/Cloud_Service_Mesh")
    ("Monitoring" . "Management_Tools/Monitoring")
    ("Cloud_PubSub" . "Data_Analytics/Cloud_PubSub")
    ("Cloud_Dataproc" . "Data_Analytics/Cloud_Dataproc")
    ("Cloud_Dataflow" . "Data_Analytics/Cloud_Dataflow")
    ("Cloud_Composer" . "Data_Analytics/Cloud_Composer")
    ("Genomics" . "Data_Analytics/Genomics")
    ("Cloud_Datalab" . "Data_Analytics/Cloud_Datalab")
    ("BigQuery" . "Data_Analytics/BigQuery")
    ("Cloud_Data_Fusion" . "Data_Analytics/Cloud_Data_Fusion")
    ("Cloud_Dataprep" . "Data_Analytics/Cloud_Dataprep")
    ("Cloud_Data_Catalog" . "Data_Analytics/Cloud_Data_Catalog")
    ("GCPCommon" . "GCPCommon")
    ("Cloud_Firestore" . "Databases/Cloud_Firestore")
    ("Cloud_Datastore" . "Databases/Cloud_Datastore")
    ("Cloud_SQL" . "Databases/Cloud_SQL")
    ("Cloud_Bigtable" . "Databases/Cloud_Bigtable")
    ("Cloud_Spanner" . "Databases/Cloud_Spanner")
    ("Cloud_Memorystore" . "Databases/Cloud_Memorystore")
    ("Networking" . "Networking")
    ("Cloud_Translation_API" . "AI_and_Machine_Learning/Cloud_Translation_API")
    ("Cloud_Speech_to_Text" . "AI_and_Machine_Learning/Cloud_Speech_to_Text")
    ("Advanced_Solutions_Lab" . "AI_and_Machine_Learning/Advanced_Solutions_Lab")
    ("AutoML_Translation" . "AI_and_Machine_Learning/AutoML_Translation")
    ("Cloud_Jobs_API" . "AI_and_Machine_Learning/Cloud_Jobs_API")
    ("AutoML_Vision" . "AI_and_Machine_Learning/AutoML_Vision")
    ("Cloud_AutoML" . "AI_and_Machine_Learning/Cloud_AutoML")
    ("AI_Hub" . "AI_and_Machine_Learning/AI_Hub")
    ("Cloud_Inference_API" . "AI_and_Machine_Learning/Cloud_Inference_API")
    ("Cloud_Natural_Language_API" . "AI_and_Machine_Learning/Cloud_Natural_Language_API")
    ("Recommendations_AI" . "AI_and_Machine_Learning/Recommendations_AI")
    ("Cloud_Vision_API" . "AI_and_Machine_Learning/Cloud_Vision_API")
    ("AutoML_Tables" . "AI_and_Machine_Learning/AutoML_Tables")
    ("AutoML_Video_Intelligence" . "AI_and_Machine_Learning/AutoML_Video_Intelligence")
    ("AutoML_Natural_Language" . "AI_and_Machine_Learning/AutoML_Natural_Language")
    ("AI_Platform" . "AI_and_Machine_Learning/AI_Platform")
    ("Cloud_Video_Intelligence_API" . "AI_and_Machine_Learning/Cloud_Video_Intelligence_API")
    ("Dialog_Flow_Enterprise_Edition" . "AI_and_Machine_Learning/Dialog_Flow_Enterprise_Edition")
    ("Cloud_TPU" . "AI_and_Machine_Learning/Cloud_TPU")
    ("Cloud_Text_to_Speech" . "AI_and_Machine_Learning/Cloud_Text_to_Speech")
    ("AI_Platform_Data_Labeling_Service" . "AI_and_Machine_Learning/AI_Platform_Data_Labeling_Service")
    ("Cloud_Security_Command_Center" . "Security/Cloud_Security_Command_Center")
    ("Key_Management_Service" . "Security/Key_Management_Service")
    ("Cloud_Resource_Manager" . "Security/Cloud_Resource_Manager")
    ("Cloud_Security_Scanner" . "Security/Cloud_Security_Scanner")
    ("Cloud_IAM" . "Security/Cloud_IAM")
    ("GCPSimplified" . "GCPSimplified")
    ("Cloud_VPN" . "Networking/Cloud_VPN")
    ("Cloud_CDN" . "Networking/Cloud_CDN")
    ("Partner_Interconnect" . "Networking/Partner_Interconnect")
    ("Standard_Network_Tier" . "Networking/Standard_Network_Tier")
    ("Cloud_NAT" . "Networking/Cloud_NAT")
    ("Cloud_Firewall_Rules" . "Networking/Cloud_Firewall_Rules")
    ("Traffic_Director" . "Networking/Traffic_Director")
    ("Cloud_Load_Balancing" . "Networking/Cloud_Load_Balancing")
    ("Virtual_Private_Cloud" . "Networking/Virtual_Private_Cloud")
    ("Cloud_External_IP_Addresses" . "Networking/Cloud_External_IP_Addresses")
    ("Cloud_Armor" . "Networking/Cloud_Armor")
    ("Premium_Network_Tier" . "Networking/Premium_Network_Tier")
    ("Cloud_DNS" . "Networking/Cloud_DNS")
    ("Dedicated_Interconnect" . "Networking/Dedicated_Interconnect")
    ("Cloud_Router" . "Networking/Cloud_Router")
    ("Cloud_Routes" . "Networking/Cloud_Routes")
    ("Cloud_Network" . "Networking/Cloud_Network")
    ("Apigee_API_Platform" . "API_Management/Apigee_API_Platform")
    ("API_Analytics" . "API_Management/API_Analytics")
    ("Developer_Portal" . "API_Management/Developer_Portal")
    ("Apigee_Sense" . "API_Management/Apigee_Sense")
    ("API_Monetization" . "API_Management/API_Monetization")
    ("Cloud_Endpoints" . "API_Management/Cloud_Endpoints")
    ("Persistent_Disk" . "Storage/Persistent_Disk")
    ("Cloud_Filestore" . "Storage/Cloud_Filestore")
    ("Cloud_Storage" . "Storage/Cloud_Storage")
    ("Cloud_Test_Lab" . "Developer_Tools/Cloud_Test_Lab")
    ("Cloud_Tools_for_Visual_Studio" . "Developer_Tools/Cloud_Tools_for_Visual_Studio")
    ("Cloud_Tools_for_PowerShell" . "Developer_Tools/Cloud_Tools_for_PowerShell")
    ("IDE_Plugins" . "Developer_Tools/IDE_Plugins")
    ("Cloud_Tasks" . "Developer_Tools/Cloud_Tasks")
    ("Cloud_Code_for_IntelliJ" . "Developer_Tools/Cloud_Code_for_IntelliJ")
    ("Maven_App_Engine_Plugin" . "Developer_Tools/Maven_App_Engine_Plugin")
    ("Cloud_Build" . "Developer_Tools/Cloud_Build")
    ("Cloud_Code" . "Developer_Tools/Cloud_Code")
    ("Gradle_App_Engine_Plugin" . "Developer_Tools/Gradle_App_Engine_Plugin")
    ("Cloud_Scheduler" . "Developer_Tools/Cloud_Scheduler")
    ("Cloud_Source_Repositories" . "Developer_Tools/Cloud_Source_Repositories")
    ("Cloud_SDK" . "Developer_Tools/Cloud_SDK")
    ("Container_Registry" . "Developer_Tools/Container_Registry")
    ("Cloud_Tools_for_Eclipse" . "Developer_Tools/Cloud_Tools_for_Eclipse")
    ("Cloud_IoT_Core" . "Internet_of_Things/Cloud_IoT_Core")
    ("Cloud_Run" . "Compute/Cloud_Run")
    ("Container_Optimized_OS" . "Compute/Container_Optimized_OS")
    ("Compute_Engine" . "Compute/Compute_Engine")
    ("GKE_On_Prem" . "Compute/GKE_On_Prem")
    ("Cloud_Functions" . "Compute/Cloud_Functions")
    ("Kubernetes_Engine" . "Compute/Kubernetes_Engine")
    ("GPU" . "Compute/GPU")
    ("App_Engine" . "Compute/App_Engine")
    ("Stackdriver" . "Hybrid_and_Multi_Cloud/Stackdriver")
    ("Traffic_Director" . "Hybrid_and_Multi_Cloud/Traffic_Director")
    ("Transfer_Appliance" . "Migration/Transfer_Appliance")
    ("GCPC4Integration" . "GCPC4Integration"))
  "List of PlantUML GCP components")

(cl-defmethod plantuml-stdlib--common-include ((library (eql 'gcp)))
  "!include <gcp/GCPCommon>")

(cl-defmethod plantuml-stdlib--prefix ((library (eql 'gcp)))
  "gcp")

(cl-defmethod plantuml-stdlib--components ((library (eql 'gcp)))
  plantuml-gcp-components)

(provide 'plantuml-stdlib-gcp)
;;; plantuml-stdlib-gcp.el
